# Use an official KrakenD base image
FROM devopsfaith/krakend

# Set the working directory inside the container
WORKDIR /app

COPY config/krakend.tmpl /app/krakend.tmpl
# Change the permissions of the file to be readable by all users
RUN chmod 644 /app/krakend.tmpl

# Actual configuration will be injected from deployment in /app/settings

# Set environment variables
ENV FC_ENABLE=1
ENV FC_SETTINGS="/app/settings"

# Expose the port KrakenD runs on
EXPOSE 8080

# Command to run KrakenD
CMD ["krakend", "run", "-c", "/app/krakend.tmpl"]
